# Generated by Django 6.0 on 2026-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "image",
                    models.ImageField(
                        upload_to="news_images/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
            ],
        ),
    ]
