# Generated by Django 6.0 on 2026-04-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="new",
            options={"verbose_name": "Tin tức", "verbose_name_plural": "Tin tức"},
        ),
    ]
