# Generated by Django 6.0 on 2026-04-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0003_classnew_competitionnew_contactnew_dailynew_news_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClassNew",
        ),
        migrations.DeleteModel(
            name="CompetitionNew",
        ),
        migrations.DeleteModel(
            name="ContactNew",
        ),
        migrations.DeleteModel(
            name="DailyNew",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
