# Generated by Django 6.0 on 2026-04-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("new", "0004_delete_classnew_delete_competitionnew_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Loại tin tức"),
                ),
            ],
            options={
                "verbose_name": "Loại tin tức",
                "verbose_name_plural": "Loại tin tức",
            },
        ),
        migrations.CreateModel(
            name="DailyNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("content_1", models.TextField(blank=True, verbose_name="Nội dung 1")),
                ("content_2", models.TextField(blank=True, verbose_name="Nội dung 2")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "images_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="daily_news/",
                        verbose_name="Hình ảnh 1",
                    ),
                ),
                (
                    "images_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="daily_news/",
                        verbose_name="Hình ảnh 2",
                    ),
                ),
                (
                    "images_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="daily_news/",
                        verbose_name="Hình ảnh 3",
                    ),
                ),
                (
                    "news_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new.news",
                        verbose_name="Loại tin tức",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng tin hàng ngày",
                "verbose_name_plural": "Bảng tin hàng ngày",
            },
        ),
        migrations.CreateModel(
            name="ContactNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("content_1", models.TextField(blank=True, verbose_name="Nội dung 1")),
                ("content_2", models.TextField(blank=True, verbose_name="Nội dung 2")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "images_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_news/",
                        verbose_name="Hình ảnh 1",
                    ),
                ),
                (
                    "images_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_news/",
                        verbose_name="Hình ảnh 2",
                    ),
                ),
                (
                    "images_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_news/",
                        verbose_name="Hình ảnh 3",
                    ),
                ),
                (
                    "news_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new.news",
                        verbose_name="Loại tin tức",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng tin liên hệ",
                "verbose_name_plural": "Bảng tin liên hệ",
            },
        ),
        migrations.CreateModel(
            name="CompetitionNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("content_1", models.TextField(blank=True, verbose_name="Nội dung 1")),
                ("content_2", models.TextField(blank=True, verbose_name="Nội dung 2")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "images_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="competition_news/",
                        verbose_name="Hình ảnh 1",
                    ),
                ),
                (
                    "images_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="competition_news/",
                        verbose_name="Hình ảnh 2",
                    ),
                ),
                (
                    "images_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="competition_news/",
                        verbose_name="Hình ảnh 3",
                    ),
                ),
                (
                    "news_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new.news",
                        verbose_name="Loại tin tức",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng tin cuộc thi",
                "verbose_name_plural": "Bảng tin cuộc thi",
            },
        ),
        migrations.CreateModel(
            name="ClassNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("content_1", models.TextField(blank=True, verbose_name="Nội dung 1")),
                ("content_2", models.TextField(blank=True, verbose_name="Nội dung 2")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "images_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="class_news/",
                        verbose_name="Hình ảnh 1",
                    ),
                ),
                (
                    "images_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="class_news/",
                        verbose_name="Hình ảnh 2",
                    ),
                ),
                (
                    "images_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="class_news/",
                        verbose_name="Hình ảnh 3",
                    ),
                ),
                (
                    "news_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new.news",
                        verbose_name="Loại tin tức",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng tin lớp học",
                "verbose_name_plural": "Bảng tin lớp học",
            },
        ),
    ]
