# Generated by Django 6.0 on 2026-04-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionnew",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="contactnew",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="dailynew",
            name="news_type",
        ),
        migrations.DeleteModel(
            name="ClassNew",
        ),
        migrations.DeleteModel(
            name="CompetitionNew",
        ),
        migrations.DeleteModel(
            name="ContactNew",
        ),
        migrations.DeleteModel(
            name="DailyNew",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
