# Generated by Django 6.0 on 2026-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="description",
            field=models.TextField(verbose_name="Mô tả khóa học"),
        ),
        migrations.AlterField(
            model_name="classes",
            name="image",
            field=models.ImageField(upload_to="classes/", verbose_name="Ảnh khóa học"),
        ),
        migrations.AlterField(
            model_name="classes",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tên khóa học"),
        ),
    ]
