# Generated by Django 6.0 on 2026-04-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_classes_description_alter_classes_image_and_more"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="description",
        ),
        migrations.AddField(
            model_name="classes",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Giá"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classes",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Số lượng học viên"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classes",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="team.teacher",
                verbose_name="Giáo viên",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="time",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Thời gian học"
            ),
            preserve_default=False,
        ),
    ]
