# Generated by Django 6.0 on 2026-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_remove_classes_description_classes_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="age",
            field=models.CharField(default=1, max_length=100, verbose_name="Độ tuổi"),
            preserve_default=False,
        ),
    ]
