# Generated by Django 6.0 on 2026-04-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_classes_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classes",
            options={"verbose_name": "Khóa học", "verbose_name_plural": "Khóa học"},
        ),
    ]
