# Generated by Django 5.2 on 2026-04-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_classes_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(max_length=255, verbose_name="Tên người giám hộ"),
                ),
                (
                    "guardian_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email người giám hộ"
                    ),
                ),
                (
                    "child_name",
                    models.CharField(max_length=255, verbose_name="Tên học viên"),
                ),
                (
                    "child_age",
                    models.CharField(max_length=50, verbose_name="Tuổi học viên"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Đăng ký",
                "verbose_name_plural": "Đăng ký",
            },
        ),
    ]
