# Generated by Django 6.0 on 2026-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0006_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả khóa học"),
        ),
    ]
