# Generated by Django 6.0 on 2026-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_classes_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Nội dung giảng dạy"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
            ],
            options={
                "verbose_name": "Nội dung giảng dạy",
                "verbose_name_plural": "Nội dung giảng dạy",
            },
        ),
        migrations.CreateModel(
            name="Objects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Đối tượng")),
                ("description", models.TextField(blank=True, verbose_name="Nội dung")),
            ],
            options={
                "verbose_name": "Đối tượng",
                "verbose_name_plural": "Đối tượng",
            },
        ),
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Chương trình học"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Nội dung")),
            ],
            options={
                "verbose_name": "Chương trình học",
                "verbose_name_plural": "Chương trình học",
            },
        ),
    ]
