# Generated by Django 6.0 on 2026-04-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_content_objects_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="classes/content/", verbose_name="Ảnh minh họa"
            ),
        ),
    ]
