# Generated by Django 6.0 on 2026-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0009_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="levels",
            field=models.CharField(blank=True, max_length=255, verbose_name="Cấp độ"),
        ),
    ]
