# Generated by Django 6.0 on 2026-04-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0010_classes_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="levels",
            field=models.TextField(blank=True, max_length=255, verbose_name="Cấp độ"),
        ),
    ]
