# Generated by Django 6.0 on 2026-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0011_alter_classes_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="guardian_email",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="area",
            field=models.CharField(
                default=True, max_length=255, verbose_name="Khu vực"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="phone",
            field=models.CharField(
                default=True, max_length=20, verbose_name="Số điện thoại"
            ),
            preserve_default=False,
        ),
    ]
