# Generated by Django 6.0 on 2026-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0012_remove_enrollment_guardian_email_enrollment_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="guardian_email",
            field=models.EmailField(default=True, max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
    ]
