# Generated by Django 6.0 on 2026-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="artist",
            field=models.CharField(max_length=100, verbose_name="Tác giả"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to="products/", verbose_name="Hình ảnh"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Tên tác phẩm"),
        ),
    ]
