# Generated by Django 6.0 on 2026-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_artist_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Đề tài"),
        ),
    ]
