# Generated by Django 6.0.3 on 2026-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='franchise/hero/')),
                ('alt_text', models.CharField(default='Sáng tạo cùng trẻ', max_length=255)),
                ('quote', models.CharField(default='Nơi ươm mầm cho những tài năng nhí tỏa sáng rực rỡ!', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ảnh Hero Nhượng Quyền',
                'verbose_name_plural': 'Ảnh Hero Nhượng Quyền',
            },
        ),
    ]
