# Generated by Django 6.0 on 2026-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên giáo viên"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="teachers/", verbose_name="Ảnh giáo viên"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Chức danh"),
                ),
                ("bio", models.TextField(verbose_name="Tiểu sử")),
            ],
            options={
                "verbose_name": "Giáo viên",
                "verbose_name_plural": "Giáo viên",
            },
        ),
    ]
