# Generated by Django 6.0 on 2026-04-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutSection",
        ),
    ]
