# Generated by Django 6.0 on 2026-04-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_aboutsection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainingPolicy",
        ),
    ]
