# Generated by Django 5.2 on 2026-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0003_delete_trainingpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="carousel/")),
                ("button1_text", models.CharField(blank=True, max_length=100)),
                ("button1_link", models.CharField(blank=True, max_length=255)),
                ("button2_text", models.CharField(blank=True, max_length=100)),
                ("button2_link", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
