# Generated by Django 6.0 on 2026-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Giới thiệu về HaHa Art", max_length=200),
                ),
                ("desc_1", models.TextField(blank=True)),
                ("desc_2", models.TextField(blank=True)),
                ("desc_3", models.TextField(blank=True)),
                ("desc_4", models.TextField(blank=True)),
                ("desc_5", models.TextField(blank=True)),
                ("image_1", models.ImageField(blank=True, upload_to="about/")),
                ("image_2", models.ImageField(blank=True, upload_to="about/")),
                ("image_3", models.ImageField(blank=True, upload_to="about/")),
            ],
            options={
                "verbose_name": "Giới thiệu",
                "verbose_name_plural": "Giới thiệu",
            },
        ),
    ]
