# Generated by Django 6.0 on 2026-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Different",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Điểm khác biệt của HaHa Art", max_length=200
                    ),
                ),
                ("desc_1", models.TextField(blank=True, verbose_name="Nội dung")),
                (
                    "image_1",
                    models.ImageField(
                        upload_to="about/different/", verbose_name="Ảnh minh họa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm khác biệt",
                "verbose_name_plural": "Điểm khác biệt",
            },
        ),
    ]
