# Generated by Django 6.0 on 2026-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_different"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Lợi ích khi tham gia HaHa Art", max_length=200
                    ),
                ),
                ("desc_1", models.TextField(blank=True, verbose_name="Nội dung")),
                (
                    "image_1",
                    models.ImageField(
                        upload_to="about/benefit/", verbose_name="Ảnh minh họa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lợi ích",
                "verbose_name_plural": "Lợi ích",
            },
        ),
        migrations.CreateModel(
            name="Promote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ưu đãi khi tham gia HaHa Art", max_length=200
                    ),
                ),
                ("desc_1", models.TextField(blank=True, verbose_name="Nội dung")),
                (
                    "image_1",
                    models.ImageField(
                        upload_to="about/promote/", verbose_name="Ảnh minh họa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ưu đãi",
                "verbose_name_plural": "Ưu đãi",
            },
        ),
    ]
