# Generated by Django 6.0 on 2026-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Quy chế đào tạo", max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="policy/")),
            ],
            options={
                "verbose_name": "Quy chế đào tạo",
                "verbose_name_plural": "Quy chế đào tạo",
            },
        ),
    ]
