# Generated by Django 6.0.3 on 2026-04-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Hành trình cảm xúc', max_length=100, verbose_name='Nhãn nhỏ phía trên tiêu đề')),
                ('title', models.CharField(default='Câu chuyện thương hiệu', max_length=255, verbose_name='Tiêu đề chính')),
                ('image', models.ImageField(upload_to='brand_story/', verbose_name='Ảnh đại diện')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ảnh (alt)')),
                ('badge_number', models.CharField(default='5+', max_length=10, verbose_name='Số hiển thị trên badge (vd: 5+)')),
                ('badge_label', models.CharField(default='Năm tâm huyết', max_length=50, verbose_name='Nhãn badge')),
                ('intro_text', models.TextField(verbose_name='Đoạn giới thiệu (dòng in nghiêng đầu tiên)')),
                ('intro_highlight', models.CharField(blank=True, max_length=255, verbose_name='Phần chữ nổi bật trong intro')),
                ('closing_quote', models.TextField(verbose_name='Câu kết (dòng chữ cam cuối)')),
                ('brand_name', models.CharField(default='HaHa Art', max_length=100, verbose_name='Tên thương hiệu (chữ ký)')),
                ('brand_tagline', models.CharField(default='Nơi ước mơ được lớn lên 🎨💛', max_length=255, verbose_name='Tagline thương hiệu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Story',
                'verbose_name_plural': 'Brand Stories',
            },
        ),
        migrations.CreateModel(
            name='BrandStoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('brush', 'Brush 🖌️'), ('sentiment_satisfied', 'Smile 😊'), ('menu_book', 'Book 📖'), ('star', 'Star ⭐'), ('favorite', 'Favorite ❤️'), ('palette', 'Palette 🎨'), ('school', 'School 🎓'), ('emoji_objects', 'Idea 💡')], default='brush', max_length=50, verbose_name='Icon (Material Symbol)')),
                ('icon_color', models.CharField(choices=[('tertiary-container', 'Cam nhạt'), ('primary-container', 'Vàng nhạt'), ('secondary-fixed', 'Cam đậm nhạt')], default='tertiary-container', max_length=50, verbose_name='Màu nền icon')),
                ('content', models.TextField(verbose_name='Nội dung đoạn văn')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('brand_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='brand_story.brandstory', verbose_name='Brand Story')),
            ],
            options={
                'verbose_name': 'Điểm nội dung',
                'verbose_name_plural': 'Các điểm nội dung',
                'ordering': ['order'],
            },
        ),
    ]
